# Generated by Django 3.2.9 on 2021-12-13 04:30

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0003_auto_20211208_0934'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_products',
            name='shop_product_image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default_shop_product', force_format='JPEG', keep_meta=True, null=True, quality=100, size=[370, 530], upload_to='shop_product_images'),
        ),
        migrations.AddField(
            model_name='shop_products',
            name='shop_product_image3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default_shop_product', force_format='JPEG', keep_meta=True, null=True, quality=100, size=[370, 530], upload_to='shop_product_images'),
        ),
    ]
