# Generated by Django 3.2.9 on 2021-12-13 05:02

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0004_auto_20211213_1330'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop_products',
            name='shop_product_image4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, default='default_shop_product', force_format='JPEG', keep_meta=True, null=True, quality=100, size=[370, 530], upload_to='shop_product_images'),
        ),
    ]
