# Generated by Django 3.2.9 on 2021-12-14 04:23

from django.db import migrations
import django_resized.forms


class Migration(migrations.Migration):

    dependencies = [
        ('product', '0005_shop_products_shop_product_image4'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop_products',
            name='shop_product_image2',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[370, 530], upload_to='shop_product_images'),
        ),
        migrations.AlterField(
            model_name='shop_products',
            name='shop_product_image3',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[370, 530], upload_to='shop_product_images'),
        ),
        migrations.AlterField(
            model_name='shop_products',
            name='shop_product_image4',
            field=django_resized.forms.ResizedImageField(blank=True, crop=None, force_format='JPEG', keep_meta=True, null=True, quality=100, size=[370, 530], upload_to='shop_product_images'),
        ),
    ]
